import { Category, CategoryRule, BudgetGoal } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'groceries',
    name: 'Groceries',
    iconName: 'ShoppingCart',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Supermarkets, organic stores, food items',
    isSystem: true,
  },
  {
    id: 'dining',
    name: 'Dining & Drinks',
    iconName: 'Utensils',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    description: 'Restaurants, coffee shops, food delivery, bars',
    isSystem: true,
  },
  {
    id: 'housing',
    name: 'Housing & Rent',
    iconName: 'Home',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Rent, mortgage, HOA fees, home repair',
    isSystem: true,
  },
  {
    id: 'utilities',
    name: 'Utilities & Internet',
    iconName: 'Zap',
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/30',
    description: 'Electricity, water, gas, home fiber internet',
    isSystem: true,
  },
  {
    id: 'transport',
    name: 'Transportation & Fuel',
    iconName: 'Car',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    description: 'Gas stations, public transport, EV charging, Uber/Lyft',
    isSystem: true,
  },
  {
    id: 'tech',
    name: 'Homelab & Tech Hardware',
    iconName: 'Server',
    color: 'text-violet-400',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Homelab servers, NAS, hard drives, cables, router gear',
    isSystem: true,
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions & Software',
    iconName: 'CreditCard',
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    description: 'VPS, cloud hosting, Github, Spotify, Netflix, domain names',
    isSystem: true,
  },
  {
    id: 'shopping',
    name: 'Shopping & Goods',
    iconName: 'ShoppingBag',
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Clothing, electronics, household appliances, online shopping',
    isSystem: true,
  },
  {
    id: 'health',
    name: 'Healthcare & Fitness',
    iconName: 'HeartPulse',
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/30',
    description: 'Gym, pharmacy, medical insurance, doctor visits',
    isSystem: true,
  },
  {
    id: 'entertainment',
    name: 'Leisure & Hobbies',
    iconName: 'Film',
    color: 'text-indigo-400',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    description: 'Movies, concerts, gaming, outdoor activities, travel',
    isSystem: true,
  },
  {
    id: 'income',
    name: 'Income & Salary',
    iconName: 'DollarSign',
    color: 'text-teal-400',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Salary, freelance work, side income, interest',
    isSystem: true,
  },
  {
    id: 'miscellaneous',
    name: 'Miscellaneous',
    iconName: 'HelpCircle',
    color: 'text-slate-400',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-500/30',
    description: 'Uncategorized or general expenses',
    isSystem: true,
  },
];

export const DEFAULT_RULES: CategoryRule[] = [
  { id: 'rule-1', keyword: 'TRADER JOE', categoryName: 'Groceries', active: true, createdAt: '2026-01-01' },
  { id: 'rule-2', keyword: 'WALMART', categoryName: 'Groceries', active: true, createdAt: '2026-01-01' },
  { id: 'rule-3', keyword: 'WHOLEFDS', categoryName: 'Groceries', active: true, createdAt: '2026-01-01' },
  { id: 'rule-4', keyword: 'STARBUCKS', categoryName: 'Dining & Drinks', active: true, createdAt: '2026-01-01' },
  { id: 'rule-5', keyword: 'UBER EATS', categoryName: 'Dining & Drinks', active: true, createdAt: '2026-01-01' },
  { id: 'rule-6', keyword: 'UBER TRIP', categoryName: 'Transportation & Fuel', active: true, createdAt: '2026-01-01' },
  { id: 'rule-7', keyword: 'CHEVRON', categoryName: 'Transportation & Fuel', active: true, createdAt: '2026-01-01' },
  { id: 'rule-8', keyword: 'SHELL OIL', categoryName: 'Transportation & Fuel', active: true, createdAt: '2026-01-01' },
  { id: 'rule-9', keyword: 'NETFLIX', categoryName: 'Subscriptions & Software', active: true, createdAt: '2026-01-01' },
  { id: 'rule-10', keyword: 'SPOTIFY', categoryName: 'Subscriptions & Software', active: true, createdAt: '2026-01-01' },
  { id: 'rule-11', keyword: 'HETZNER', categoryName: 'Subscriptions & Software', active: true, createdAt: '2026-01-01' },
  { id: 'rule-12', keyword: 'DIGITALOCEAN', categoryName: 'Subscriptions & Software', active: true, createdAt: '2026-01-01' },
  { id: 'rule-13', keyword: 'NEWEGG', categoryName: 'Homelab & Tech Hardware', active: true, createdAt: '2026-01-01' },
  { id: 'rule-14', keyword: 'MICRO CENTER', categoryName: 'Homelab & Tech Hardware', active: true, createdAt: '2026-01-01' },
  { id: 'rule-15', keyword: 'AMAZON AWS', categoryName: 'Subscriptions & Software', active: true, createdAt: '2026-01-01' },
  { id: 'rule-16', keyword: 'PAYROLL', categoryName: 'Income & Salary', active: true, createdAt: '2026-01-01' },
  { id: 'rule-17', keyword: 'PG&E', categoryName: 'Utilities & Internet', active: true, createdAt: '2026-01-01' },
  { id: 'rule-18', keyword: 'COMCAST', categoryName: 'Utilities & Internet', active: true, createdAt: '2026-01-01' },
];

export const DEFAULT_BUDGETS: BudgetGoal[] = [
  { categoryId: 'groceries', categoryName: 'Groceries', monthlyLimit: 600, warnThresholdPercent: 80 },
  { categoryId: 'dining', categoryName: 'Dining & Drinks', monthlyLimit: 300, warnThresholdPercent: 80 },
  { categoryId: 'housing', categoryName: 'Housing & Rent', monthlyLimit: 1800, warnThresholdPercent: 90 },
  { categoryId: 'utilities', categoryName: 'Utilities & Internet', monthlyLimit: 250, warnThresholdPercent: 80 },
  { categoryId: 'transport', categoryName: 'Transportation & Fuel', monthlyLimit: 250, warnThresholdPercent: 80 },
  { categoryId: 'tech', categoryName: 'Homelab & Tech Hardware', monthlyLimit: 400, warnThresholdPercent: 85 },
  { categoryId: 'subscriptions', categoryName: 'Subscriptions & Software', monthlyLimit: 150, warnThresholdPercent: 80 },
  { categoryId: 'shopping', categoryName: 'Shopping & Goods', monthlyLimit: 350, warnThresholdPercent: 80 },
  { categoryId: 'entertainment', categoryName: 'Leisure & Hobbies', monthlyLimit: 200, warnThresholdPercent: 80 },
];
